export default {
    GET_TODOS_SUCCESS:'GET_TODOS_SUCCESS',
    ADD_TODOS_SUCCESS:'ADD_TODOS_SUCCESS',
    DELETE_TODOS:'DELETE_TODOS',
    GET_TODOS_CHECKED:'GET_TODOS_CHECKED',
    SELECT_ALL_TODOS:'SELECT_ALL_TODOS'
};