export default {
    MARK_NOTIFICATION_AS_READ_BY_ID:'MARK_NOTIFICATION_AS_READ_BY_ID', //标记已读

    MARK_ALL_NOTIFICATION_AS_READ_BY_ID:'MARK_ALL_NOTIFICATION_AS_READ_BY_ID', //全部标记已读

    START_MARK_AS_READ:'START_MARK_AS_READ', //修改通知状态loading
    FINISH_MARK_AS_READ:'FINISH_MARK_AS_READ',

    RECEIVED_NOTIFICATION_LIST:'RECEIVED_NOTIFICATION_LIST',//得到通知列表,给reducer 传参

    START_LOGIN:'START_LOGIN', //登录状态
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_FAILED:'LOGIN_FAILED',

    CHANGE_AVATAR:'CHANGE_AVATAR' //修改头像
}

